name: Quick Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    name: Core Test
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test requirements
      run: |
        python -m pip install -U pip setuptools wheel twine
        pip install pytest pycryptodomex
        python -m pip install -U Pyinstaller -r requirements.txt
    - name: Run tests
      run: |
        python3 -m yt_dlp -v || true
        ./devscripts/run_tests.sh core
  flake8:
    name: Linter
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install flake8
      run: pip install flake8
    - name: Install requirements
      run: |
        python -m pip install -U pip setuptools wheel twine
        python -m pip install -U Pyinstaller -r requirements.txt
    - name: Make lazy extractors
      run: python devscripts/make_lazy_extractors.py
    - name: Run flake8
      run: flake8 .
